DROP TABLE BOOK_TO_CLASS;
DROP TABLE CLASS;
DROP TABLE BOOK;
DROP TABLE EMPLOYEE;
DROP TABLE JOBS;

DROP SEQUENCE book_to_class_id;
DROP SEQUENCE class_id;
DROP SEQUENCE book_id;
DROP SEQUENCE employee_id;
DROP SEQUENCE job_id;
